FROM python:latest

RUN apt-get -y update &&  apt -y update
RUN pip install seaborn
RUN pip3 install -U scikit-learn
RUN pip3 install -U pandas

WORKDIR /app

COPY . .

CMD [ "python","./classification_103.py" ]